server:
  port: 20000
  servlet:
    session:
      timeout: 30m
spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  thymeleaf:
    cache: false
  redis:
    host: 192.168.233.200
    port: 6379
  session:
    store-type: redis

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

