server:
  port: 12000

spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.233.200
    port: 6379
  session:
    store-type: redis
  thymeleaf:
    cache: false

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
