server:
  port: 12000

spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
  redis:
    host: 192.168.233.200
    port: 6379
  session:
    store-type: redis
  thymeleaf:
    cache: false
  zipkin:
    base-url: http://192.168.233.200:9411/
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

#开启对远程Feign支持
feign:
  sentinel:
    enabled: true

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
