spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      oss:
        endpoint: oss-cn-qingdao.aliyuncs.com
        bucket: gulimall-chenjianrui
  application:
    name: gulimall-third-part
server:
  port: 30000
