spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      oss:
        endpoint: oss-cn-qingdao.aliyuncs.com
        bucket: gulimall-chenjianrui
      access-key: LTAI5tEaGoQ98K7wGVechS91
      secret-key: I35C2Xf8yQc5VCqx4syxNiyyOscZbd
      sms:
        host: http://jnlzsms.market.alicloudapi.com
        path: /lundroid/smsSend
        appcode: 581ed3441519456ca7897d9a8b894cef
        templateId: SMS_75800186
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
  application:
    name: gulimall-third-part
server:
  port: 30000

#开启对远程Feign支持
feign:
  sentinel:
    enabled: true

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
