server:
  port: 40000

spring:
  application:
    name: gulimall-cart
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: 127.0.0.1:8080
  redis:
    port: 6379
    host: 192.168.233.200
  session:
    store-type: redis

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true


#配置线程池
gulimall:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'


